#!/usr/bin/env python3
"""Bind COMPILE_REPORT.md to the exact bytes of the final PDF."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path


MARKER = "MODEX_PDF_SNAPSHOT_V1"
BLOCK_START = "<!-- MODEX_PDF_SNAPSHOT_BEGIN -->"
BLOCK_END = "<!-- MODEX_PDF_SNAPSHOT_END -->"

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass


def _page_count(path: Path) -> int:
    try:
        from pypdf import PdfReader

        return len(PdfReader(str(path)).pages)
    except Exception:
        executable = shutil.which("pdfinfo")
        if executable:
            result = subprocess.run(
                [executable, str(path)], stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                text=True, encoding="utf-8", errors="replace", timeout=30, check=False,
            )
            match = re.search(r"(?mi)^Pages:\s*(\d+)\s*$", result.stdout)
            if result.returncode == 0 and match:
                return int(match.group(1))
    raise RuntimeError("无法读取最终 PDF 页数（需要 pypdf 或 pdfinfo）")


def snapshot(path: Path) -> dict[str, object]:
    if not path.is_file() or path.stat().st_size == 0:
        raise RuntimeError(f"最终 PDF 不存在或文件为空: {path}")
    before = path.stat()
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    pages = _page_count(path)
    after = path.stat()
    if (before.st_size, before.st_mtime_ns) != (after.st_size, after.st_mtime_ns):
        raise RuntimeError("PDF 在快照检查期间发生变化，请在导出结束后核对")
    if pages < 1:
        raise RuntimeError("最终 PDF 没有页面")
    return {
        "pdf": path.as_posix(),
        "sha256": digest.hexdigest(),
        "bytes": after.st_size,
        "pages": pages,
    }


def write_report(pdf: Path, report: Path) -> dict[str, object]:
    data = snapshot(pdf)
    data["captured_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    payload = json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    original = report.read_text(encoding="utf-8") if report.exists() else ""
    starts, ends = original.count(BLOCK_START), original.count(BLOCK_END)
    if starts != ends or starts > 1 or (starts == 1 and original.index(BLOCK_END) < original.index(BLOCK_START)):
        raise RuntimeError("编译报告快照区块不完整，已保留原报告，需核对区块边界")
    retained = re.sub(re.escape(BLOCK_START) + r"[\s\S]*?" + re.escape(BLOCK_END), "", original)
    # Migrate only the exact old autogenerated snapshot section. Never replace
    # the whole report: it may contain unresolved checks and their evidence.
    retained = re.sub(
        r"# 最终 PDF 编译报告\n\n> 本报告由程序在最后一次质量检查后生成，页数与哈希均绑定到同一个 PDF 文件。\n\n"
        r"(?:- (?:文件：|实际总页数：|文件大小：|SHA-256：|快照时间（UTC）：)[^\n]*\n)+\n"
        + rf"<!--\s*{MARKER}\s+\{{[^\n]*\}}\s*-->\n?", "", retained,
    )
    retained = re.sub(rf"<!--\s*{MARKER}\s+\{{[^\n]*\}}\s*-->", "", retained)
    content = (retained.rstrip() or "# 最终 PDF 编译报告") + "\n\n" + (
        f"{BLOCK_START}\n## 最终 PDF 文件快照\n\n"
        "> 以下仅证明文件版本、页数与哈希一致，不代表其他质量检查已通过。此前检查结论保留，是否仍适用需核对其输入版本。\n\n"
        f"- 文件：`{data['pdf']}`\n"
        f"- 实际总页数：**{data['pages']} 页**\n"
        f"- 文件大小：{data['bytes']} 字节\n"
        f"- SHA-256：`{data['sha256']}`\n"
        f"- 快照时间（UTC）：{data['captured_at']}\n\n"
        f"<!-- {MARKER} {payload} -->\n{BLOCK_END}\n"
    )
    report.parent.mkdir(parents=True, exist_ok=True)
    temp = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="\n",
                                         dir=report.parent, prefix=report.name + ".", suffix=".tmp",
                                         delete=False) as handle:
            temp = Path(handle.name)
            handle.write(content)
        if (report.read_text(encoding="utf-8") if report.exists() else "") != original:
            raise RuntimeError("编译报告在更新期间被修改，已保留其他写入，请重新核对")
        os.replace(temp, report)
    finally:
        if temp is not None:
            temp.unlink(missing_ok=True)
    return data


def check_report(pdf: Path, report: Path) -> tuple[bool, str]:
    if not report.is_file():
        return False, f"未找到与最终 PDF 绑定的 {report.name}"
    text = report.read_text(encoding="utf-8", errors="replace")
    matches = re.findall(rf"<!--\s*{MARKER}\s+(\{{.*?\}})\s*-->", text)
    if len(matches) != 1:
        return False, f"{report.name} 缺少或包含多个 PDF 快照标记"
    try:
        recorded = json.loads(matches[0])
        current = snapshot(pdf)
    except (json.JSONDecodeError, OSError, RuntimeError) as exc:
        return False, str(exc)
    for key in ("sha256", "bytes", "pages"):
        if recorded.get(key) != current.get(key):
            return False, f"{report.name} 已过期：{key} 与最终 PDF 不一致"
    return True, f"PDF 快照一致：{current['pages']} 页，SHA-256 {str(current['sha256'])[:12]}…"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("sync", "check"))
    parser.add_argument("pdf", type=Path)
    parser.add_argument("--report", type=Path, default=Path("COMPILE_REPORT.md"))
    args = parser.parse_args(argv)
    try:
        if args.command == "sync":
            data = write_report(args.pdf, args.report)
            print(f"  OK: 编译报告已绑定最终 PDF（{data['pages']} 页，SHA-256 {str(data['sha256'])[:12]}…）")
            return 0
        ok, detail = check_report(args.pdf, args.report)
        print(("  OK: " if ok else "  FAIL: ") + detail)
        return 0 if ok else 1
    except (OSError, RuntimeError) as exc:
        print(f"  FAIL: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
