"""Wrapper: humanities_review.py → humanities_review.pyc

Auto-generated by production audit. Skills reference .py but the tool is .pyc.
Python 3.11+ can load .pyc as a module; this wrapper enables script execution.
"""
import sys, importlib.util, os as _os

_pyc_path = _os.path.join(_os.path.dirname(__file__), "humanities_review.pyc")
if _os.path.exists(_pyc_path):
    _spec = importlib.util.spec_from_file_location("__main__", _pyc_path)
    _mod = importlib.util.module_from_spec(_spec)
    sys.modules["__main__"] = _mod
    _spec.loader.exec_module(_mod)
else:
    print(f"ERROR: humanities_review.pyc not found at {_pyc_path}")
    sys.exit(1)
