# -*- coding: utf-8 -*-
"""
pyc_loader.py — 通用 .pyc 加载器（跨 Python 小版本兼容）

背景：tools/ 下部分工具以 .pyc 分发（Python 3.11 编译，magic 0x0a0d0da7），
当前默认环境为 Python 3.12+（magic 0x0a0d0dcb）。

两个加载路径：
  1. 优先：找到 Python 3.11 venv（.venv311），用 subprocess 原生运行 .pyc
     （字节码语义完全一致，最可靠）
  2. 回退：marshal 手动加载 code object（3.11→3.12 相邻版本 marshal 格式稳定，
     但部分 opcode 语义差异可能导致运行时错误）

用法：
  python pyc_loader.py <xxx.pyc> [args...]
"""
import os
import sys
import marshal
import pathlib
import subprocess

# .venv311 位置：优先套件根目录，其次工作区根
_VENV_CANDIDATES = [
    pathlib.Path(__file__).resolve().parent.parent / '.venv311',   # 数学建模全流程套件/.venv311
    pathlib.Path(__file__).resolve().parent.parent.parent / '.venv311',  # 工作区根/.venv311
]
_VENV_PY = None
for _c in _VENV_CANDIDATES:
    _p = _c / 'Scripts' / 'python.exe'
    if _p.exists():
        _VENV_PY = str(_p)
        break


def find_py311_venv():
    """查找 Python 3.11 venv 的 python.exe，未找到返回 None。"""
    return _VENV_PY


def load_code_from_pyc(pyc_path: pathlib.Path):
    """跳过 pyc 头部（magic 4 + flags 4 + mtime 4 + size 4），用 marshal 加载 code object。"""
    with open(pyc_path, 'rb') as f:
        f.read(16)
        code = marshal.load(f)
    return code


def run_pyc_native(pyc_path: pathlib.Path, argv: list = None):
    """用 Python 3.11 venv 原生运行 .pyc（推荐路径）。"""
    py = find_py311_venv()
    if not py:
        return False
    cmd = [py, str(pyc_path)] + (argv or [])
    try:
        r = subprocess.run(cmd, cwd=str(pyc_path.parent))
    except Exception:
        return False
    sys.exit(r.returncode)
    return True


def run_pyc_marshal(pyc_path: pathlib.Path, argv: list = None):
    """回退路径：marshal 手动加载 code object 执行。"""
    code = load_code_from_pyc(pyc_path)
    globals_dict = {
        '__name__': '__main__',
        '__file__': str(pyc_path),
        '__package__': None,
        '__spec__': None,
        '__doc__': None,
        '__builtins__': __builtins__,
    }
    sys.argv = [str(pyc_path)] + (argv or [])
    exec(code, globals_dict, globals_dict)


def run_pyc(pyc_path: pathlib.Path, argv: list = None):
    """运行 .pyc：优先 venv311 原生，回退 marshal。"""
    if not run_pyc_native(pyc_path, argv):
        run_pyc_marshal(pyc_path, argv)


def build_wrappers(tools_dir: pathlib.Path, force: bool = False):
    """为 tools/ 下所有 .pyc 生成/更新 .py wrapper（优先 venv311，回退 marshal）。"""
    wrapper_template = '''# -*- coding: utf-8 -*-
"""Auto-generated wrapper for {pyc_name} (Python 3.11 pyc).

Generated by tools/pyc_loader.py — runs via .venv311 (Python 3.11) natively,
falls back to marshal loading on the current interpreter.
"""
import sys
import pathlib
import os as _os

_pyc_path = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "{pyc_name}")
if not _os.path.exists(_pyc_path):
    print(f"ERROR: {pyc_name} not found at {{_pyc_path}}")
    sys.exit(1)

# 确保 tools/ 在 sys.path（供兄弟模块导入）
_tools_dir = _os.path.dirname(_os.path.abspath(__file__))
if _tools_dir not in sys.path:
    sys.path.insert(0, _tools_dir)

from pyc_loader import run_pyc
run_pyc(pathlib.Path(_pyc_path), sys.argv[1:])
'''
    built = []
    for pyc in sorted(tools_dir.glob('*.pyc')):
        py = pyc.with_suffix('.py')
        need_write = force or not py.exists() or 'pyc_loader' not in py.read_text(encoding='utf-8', errors='replace')
        if need_write:
            py.write_text(wrapper_template.format(pyc_name=pyc.name), encoding='utf-8')
            built.append(pyc.name)
    return built


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    target = pathlib.Path(sys.argv[1])
    if not target.exists():
        print(f"ERROR: {target} not found")
        sys.exit(1)
    run_pyc(target, sys.argv[2:])