# -*- coding: utf-8 -*-
"""Auto-generated wrapper for docx_template_fill.pyc (Python 3.11 pyc).

Generated by tools/pyc_loader.py — runs via .venv311 (Python 3.11) natively,
falls back to marshal loading on the current interpreter.
"""
import sys
import pathlib
import os as _os

_pyc_path = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "docx_template_fill.pyc")
if not _os.path.exists(_pyc_path):
    print(f"ERROR: docx_template_fill.pyc not found at {_pyc_path}")
    sys.exit(1)

# 确保 tools/ 在 sys.path（供兄弟模块导入）
_tools_dir = _os.path.dirname(_os.path.abspath(__file__))
if _tools_dir not in sys.path:
    sys.path.insert(0, _tools_dir)

if __name__ == "__main__":
    from pyc_loader import run_pyc
    run_pyc(pathlib.Path(_pyc_path), sys.argv[1:])
else:
    # 被兄弟模块 import：符号须落进本模块命名空间（见 pyc_loader.import_pyc_module）
    from pyc_loader import import_pyc_module
    import_pyc_module(pathlib.Path(_pyc_path), globals())
